
**In here i will show how we save our trained model into folder so that you can share with your friends 
or other mates for prediction or checking the accuracy**

#### Step 1: Importing basic liabarys

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

####  Step 2 : Reading the dataset

In [3]:
df = pd.read_csv(r"E:\LEARNING AI\supervised ml/homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

#### Step 3 : Splitting x(INPUT CLOUMNS) and y (OUTPUT COLUMNS)for prection


**Before that i want to say you that never put complete row of x and y column in 
prediction it is not the best practise in industry , in industry train test split method used before prediction , 
i will teach you about it in train test split directory, here i just teach yo to how to save model**

In [4]:
x_df = df.drop(['price'],axis=1)
x_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [5]:
y_df=df['price']
y_df

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

### STEP 4 :Creating Linear regression object

In [6]:
# create linear reg object
lr=LinearRegression()
# I fitting x and y in lr to find best line for getting M and B
lr.fit(x_df,y_df)

LinearRegression()

In [7]:
#For seeing M(gradient or slope) of best line
lr.coef_

array([135.78767123])

In [8]:
#For seeing b(Y-intercept) of best line
lr.intercept_

180616.43835616432

**Now we have created a trained model storing inside lr object  nowour 
next step is to save it...For that i use 2 liabary for saving process**
#### 1 , Pickle liabary
#### 2, Joblib liabary

#### Pickle File

In [9]:
import pickle

In [10]:
with open("lrmodel",'wb') as file:
    #in this step we had created a file naming lr model
    # wb means write binary ,ie for saving we say write 'w' and for loading we say read ie 'r'
    pickle.dump(lr,file)
    #in this step we are dumping, dump meaing putting model inside the file 

    #This is the wy we can share our model to colligeus


In [11]:
with open("lrmodel",'rb') as file:
    mp = pickle.load(file)
    # in here we reading the saved model from the folder, since it saves in same folder i just call its name
     #This the way our colliges can read our file


In [12]:

# Checking the readed file showing same value in coifficent (M) and intercept (Y)
mp.coef_

array([135.78767123])

In [13]:
mp.predict([[5000]])

array([859554.79452055])

In [14]:
### create a file named sample.json with some data:
#In here i just showing how anormal file can save in json format
#Remember that only pickle and joblib method is the only option  to save ML model 
import json

sampleJson = {
    "name": "Luminar",
    "place": "Kochi",
    "phonenumber":"8714135828"
}

json_object = json.dumps(sampleJson)

In [15]:
with open("sample.json","w") as file:
    file.write(json_object)

In [16]:
with open("sample.json","r") as file:
    newdata = json.load(file)

In [17]:
newdata

{'name': 'Luminar', 'place': 'Kochi', 'phonenumber': '8714135828'}

#### Save trained model using Joblib

In [18]:
import joblib 

In [19]:
joblib.dump(lr,'joblibmodel')

['joblibmodel']

In [20]:
mj = joblib.load('joblibmodel')

In [21]:
mj.coef_

array([135.78767123])

In [22]:
mj.intercept_

180616.43835616432

In [23]:
joblib.load('lrmodel')

LinearRegression()